### PR TITLE
Add logs around resolving a container runtime

### PR DESCRIPTION
**Pull request by cristianrgreco**
To help debug #785

### CODE REVIEW

**Comment by cristianrgreco** [comment]
Unable to get the project to build after repeated attempts. Though the only change is the addition of logs, the GH action agents are failing to install dependencies. Either an issue with the agents or NPM 🤷

**Comment by jonesbusy** [comment]
Thanks, if you are able to release it I'm more that happy to test it and provide those logs

**Comment by jonesbusy** [comment]
Thanks but sadly I will not be able to test before 2 weeks. In any case I think those logs are useful.

So if anyone else want to test the future version and provide logs I'm very curious to know the cause of the issue

**Comment by cristianrgreco** [comment]
Thanks @jonesbusy. I think the issue may be specific to kubedock as I haven't heard anything else, so we may well have to wait for your return. Apologies this took so long to merge it turns out that https://github.com/marketplace/actions/rootless-docker has suddenly stopped working on the GH actions agents 🤷

**Pull request merged**
