### PR TITLE
docs: troubleshooting for docker compose v2

### PR DESCRIPTION
**Pull request by gastonfournier**
To support v2 it'd be necessary to change https://github.com/testcontainers/testcontainers-node/blob/f3d896b8e77b7184f0c0ac28a3d1fdad7277571f/src/docker-compose/functions/docker-compose-up.ts#L2 importing v2 functions (see https://github.com/PDMLab/docker-compose#example).

It might be possible to have 2 operation modes, but this documentation should be enough for now

### CODE REVIEW

**Comment by cristianrgreco** [comment]
Hi @gastonfournier, thanks for raising! This is related to https://github.com/testcontainers/testcontainers-node/discussions/615 which was also opened recently. Testcontainers tries to detect existence of docker-compose on initialisation, which as you noted by default is v1. So I should be able to fallback to v2 if it doesn't exist.

**Comment by cristianrgreco** [comment]
@walter-db, @gastonfournier, could you please try testcontainers version 9.12.0-beta.0? It's a release of https://github.com/testcontainers/testcontainers-node/pull/620 which will automatically fallback to v2. @gastonfournier I'm particularly interested in your compatibility case.

**Comment by sovcharenko** [comment]
hey @cristianrgreco 

we have a bunch of compose v2 files that we'd like to run with testcontainers. while locally it works perfectly because Docker Desktop redirects docker-compose to docker compose. in github actions it doesn't work and all our tests fail with 

'name' does not match any of the regexes: '^x-'

i've tried 9.12.0-beta.0 making sure that `PATH` doesn't have a reference to `docker-compose` but it didn't work

github actions environment:

```
$ echo $PATH 
/opt/hostedtoolcache/node/18.16.1/x64/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$ which docker
/usr/bin/docker

$ which docker-compose
/usr/local/bin/docker-compose


$ export PATH=/opt/hostedtoolcache/node/18.16.1/x64/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
# this is the same path as above but w/o /usr/local/bin

$ run tests ...
'name' does not match any of the regexes: '^x-'

**Comment by cristianrgreco** [comment]
@sovcharenko The error `'name' does not match any of the regexes: '^x-'` doesn't look like it comes from testcontainers. Could you share the logs (`export DEBUG=testcontainers*`) for 9.12.0-beta.0?

**Comment by sovcharenko** [comment]
```
2023-07-20T12:49:23.813Z testcontainers [INFO] Starting DockerCompose environment "testcontainers-00aece5b5a6e"...
2023-07-20T12:49:23.814Z testcontainers [DEBUG] Testing Docker client strategy "UnixSocketStrategy" with URI "unix:///var/run/docker.sock"...
2023-07-20T12:49:23.828Z testcontainers [DEBUG] Fetching system info...
2023-07-20T12:49:24.394Z testcontainers [DEBUG] Node version: v18.16.1, Platform: linux, Arch: x64, OS: Ubuntu 20.04.6 LTS, Version: 20.10.25+azure-2, Arch: x86_64, CPUs: 2, Memory: 7268704256, Compose installed: true, Compose version: 1.29.2, Compose compatibility: v1
2023-07-20T12:49:24.396Z testcontainers [DEBUG] Acquiring lock file "/tmp/tc.lock"...
2023-07-20T12:49:24.399Z testcontainers [DEBUG] Acquired lock file "/tmp/tc.lock"
2023-07-20T12:49:24.401Z testcontainers [DEBUG] Creating new Reaper for session "819a2aebc39f" with socket path "/var/run/docker.sock"...
2023-07-20T12:49:24.405Z testcontainers [INFO] Pulling image "testcontainers/ryuk:0.5.1"...
2023-07-20T12:49:24.405Z testcontainers [DEBUG] Auth config found for registry "https://index.docker.io/v1/": Auths
2023-07-20T12:49:24.578Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pulling from testcontainers/ryuk","id":"0.5.1"}
2023-07-20T12:49:24.674Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pulling fs layer","progressDetail":{},"id":"91d30c5bc195"}
2023-07-20T12:49:24.674Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pulling fs layer","progressDetail":{},"id":"44dc6ed559e0"}
2023-07-20T12:49:24.674Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pulling fs layer","progressDetail":{},"id":"3937553ff7d0"}
2023-07-20T12:49:24.714Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Downloading","progressDetail":{"current":3456,"total":284767},"progress":"[\u003e                                                  ]  3.456kB/284.8kB","id":"44dc6ed559e0"}
2023-07-20T12:49:24.717Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Downloading","progressDetail":{"current":284767,"total":284767},"progress":"[==================================================\u003e]  284.8kB/284.8kB","id":"44dc6ed559e0"}
2023-07-20T12:49:24.717Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Verifying Checksum","progressDetail":{},"id":"44dc6ed559e0"}
2023-07-20T12:49:24.718Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Download complete","progressDetail":{},"id":"44dc6ed559e0"}
2023-07-20T12:49:24.718Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Downloading","progressDetail":{"current":28097,"total":2775904},"progress":"[\u003e                                                  ]   28.1kB/2.776MB","id":"3937553ff7d0"}
2023-07-20T12:49:24.719Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Downloading","progressDetail":{"current":28749,"total":2807803},"progress":"[\u003e                                                  ]  28.75kB/2.808MB","id":"91d30c5bc195"}
2023-07-20T12:49:24.736Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Verifying Checksum","progressDetail":{},"id":"3937553ff7d0"}
2023-07-20T12:49:24.736Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Download complete","progressDetail":{},"id":"3937553ff7d0"}
2023-07-20T12:49:24.741Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Verifying Checksum","progressDetail":{},"id":"91d30c5bc195"}
2023-07-20T12:49:24.741Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Download complete","progressDetail":{},"id":"91d30c5bc195"}
2023-07-20T12:49:24.742Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":32768,"total":2807803},"progress":"[\u003e                                                  ]  32.77kB/2.808MB","id":"91d30c5bc195"}
2023-07-20T12:49:24.842Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":2031616,"total":2807803},"progress":"[====================================\u003e              ]  2.032MB/2.808MB","id":"91d30c5bc195"}
2023-07-20T12:49:24.865Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":2807803,"total":2807803},"progress":"[==================================================\u003e]  2.808MB/2.808MB","id":"91d30c5bc195"}
2023-07-20T12:49:24.889Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pull complete","progressDetail":{},"id":"91d30c5bc195"}
2023-07-20T12:49:24.890Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":32768,"total":284767},"progress":"[=====\u003e                                             ]  32.77kB/284.8kB","id":"44dc6ed559e0"}
2023-07-20T12:49:24.949Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":284767,"total":284767},"progress":"[==================================================\u003e]  284.8kB/284.8kB","id":"44dc6ed559e0"}
2023-07-20T12:49:24.956Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":284767,"total":284767},"progress":"[==================================================\u003e]  284.8kB/284.8kB","id":"44dc6ed559e0"}
2023-07-20T12:49:25.037Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pull complete","progressDetail":{},"id":"44dc6ed559e0"}
2023-07-20T12:49:25.039Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":32768,"total":2775904},"progress":"[\u003e                                                  ]  32.77kB/2.776MB","id":"3937553ff7d0"}
2023-07-20T12:49:25.136Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Extracting","progressDetail":{"current":2775904,"total":2775904},"progress":"[==================================================\u003e]  2.776MB/2.776MB","id":"3937553ff7d0"}
2023-07-20T12:49:25.162Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Pull complete","progressDetail":{},"id":"3937553ff7d0"}
2023-07-20T12:49:25.167Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Digest: sha256:533abc56c07b52a26c955d1e7ae428d810582ab01c15[638](https://github.com/BeameryHQ/enigma-monorepo/actions/runs/5611177612/jobs/10267151418#step:17:669)4ae79960eb5fa0775"}
2023-07-20T12:49:25.168Z testcontainers:pull [testcontainers/ryuk:0.5.1] {"status":"Status: Downloaded newer image for testcontainers/ryuk:0.5.1"}
2023-07-20T12:49:25.170Z testcontainers [INFO] Creating container for image "testcontainers/ryuk:0.5.1"...
2023-07-20T12:49:25.191Z testcontainers [INFO] [524d9041ab9d] Created container for image "testcontainers/ryuk:0.5.1"
2023-07-20T12:49:25.191Z testcontainers [INFO] [524d9041ab9d] Starting container for image "testcontainers/ryuk:0.5.1"...
2023-07-20T12:49:25.492Z testcontainers [INFO] [524d9041ab9d] Started container for image "testcontainers/ryuk:0.5.1"
2023-07-20T12:49:25.498Z testcontainers [DEBUG] [524d9041ab9d] Waiting for container to be ready...
2023-07-20T12:49:25.498Z testcontainers [DEBUG] [524d9041ab9d] Waiting for log message "/.+ Started!/"...
2023-07-20T12:49:25.499Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Pinging Docker...
2023-07-20T12:49:25.499Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Docker daemon is available!
2023-07-20T12:49:25.499Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Starting on port 8080...
2023-07-20T12:49:25.499Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Started!
2023-07-20T12:49:25.501Z testcontainers [DEBUG] [524d9041ab9d] Log wait strategy complete
2023-07-20T12:49:25.502Z testcontainers [INFO] [524d9041ab9d] Container is ready
2023-07-20T12:49:25.502Z testcontainers [DEBUG] [524d9041ab9d] Connecting to Reaper (attempt 1) on "localhost:32768"...
2023-07-20T12:49:25.518Z testcontainers [DEBUG] [524d9041ab9d] Connected to Reaper
2023-07-20T12:49:25.519Z testcontainers [DEBUG] Releasing lock file "/tmp/tc.lock"...
2023-07-20T12:49:25.520Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 New client connected: 172.17.0.1:50[640](https://github.com/BeameryHQ/enigma-monorepo/actions/runs/5611177612/jobs/10267151418#step:17:671)
2023-07-20T12:49:25.520Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Adding {"label":{"org.testcontainers.session-id=819a2aebc39f":true}}
2023-07-20T12:49:25.520Z testcontainers [DEBUG] Released lock file "/tmp/tc.lock"
2023-07-20T12:49:25.520Z testcontainers [INFO] Docker client strategy "UnixSocketStrategy" works, localhost (::1, 127.0.0.1)
2023-07-20T12:49:25.521Z testcontainers [INFO] Upping DockerCompose environment...
2023-07-20T12:49:25.532Z testcontainers:containers [524d9041ab9d] 2023/07/20 12:49:25 Adding {"label":{"com.docker.compose.project=testcontainers-00aece5b5a6e":true}}
2023-07-20T12:49:26.040Z testcontainers:compose The Compose file './compose-deps.yml' is invalid because:
2023-07-20T12:49:26.040Z testcontainers:compose 'name' does not match any of the regexes: '^x-'
2023-07-20T12:49:26.040Z testcontainers:compose You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
2023-07-20T12:49:26.040Z testcontainers:compose For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Error: -20T12:49:26.097Z testcontainers [ERROR] Failed to up DockerCompose environment: The Compose file './compose-deps.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
2023-07-20T12:49:26.098Z testcontainers [INFO] Downing DockerCompose environment...
2023-07-20T12:49:26.612Z testcontainers:compose The Compose file './compose-deps.yml' is invalid because:
2023-07-20T12:49:26.612Z testcontainers:compose 'name' does not match any of the regexes: '^x-'
2023-07-20T12:49:26.612Z testcontainers:compose You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
2023-07-20T12:49:26.612Z testcontainers:compose For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Error: -20T12:49:26.[664](https://github.com/BeameryHQ/enigma-monorepo/actions/runs/5611177612/jobs/10267151418#step:17:695)Z testcontainers [ERROR] Failed to down DockerCompose environment: The Compose file './compose-deps.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Error: -20T12:49:26.664Z testcontainers [ERROR] Failed to down DockerCompose environment after failed up
```

i can replicate the same error by running `docker-compose -f ./compose-deps.yml config`

on the other hand running `docker compose -f ./compose-deps.yml config` is succeeding

**Comment by sovcharenko** [comment]
This is our ./compose-deps.yml

https://docs.redpanda.com/docs/get-started/quick-start/

**Comment by sovcharenko** [comment]
riiight... so if i drop `name` from yml file it works

**Comment by gastonfournier** [comment]
@cristianrgreco I've tested the following scenarios:

### 1. Having docker-compose (v1) in the path
- testcontainers 9.11.0 works
- testcontainers 9.12.0-beta.0 works

### 2. Removing docker-compose (v1) from the path
- testcontainers 9.11.0 does not works
- testcontainers 9.12.0-beta.0 works

### 3. Having docker-compose as an alias of `docker compose --compatibility` (not something I'd recommend based on my experience)
- testcontainers 9.11.0 does not works
- testcontainers 9.12.0-beta.0 works

In both cases, docker compose (v2) is available in the path

Your solution seems to work, but let me know if I can help you test something else.

**Comment by cristianrgreco** [comment]
Thanks a lot @gastonfournier. I will release this change shortly and will update here once complete

**Comment by cristianrgreco** [comment]
Released in [9.12.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v9.12.0)

**Pull request closed without merging**
