### PR TITLE
Fixes broken readme example

### PR DESCRIPTION
**Pull request by ltwlf**
The example in the md had some issue.

### CODE REVIEW

**Comment by cristianrgreco** [comment]
nice one, let me know if ready to merge

**Comment by ltwlf** [comment]
Ready :)

**Comment by cristianrgreco** [comment]
Releasing now in 3.3.1

**Comment by ltwlf** [comment]
Great! :)

**Comment by ltwlf** [comment]
I (unfortunately) still have ideas to improve ;-) I'm also going to publish a neo4j-jest preset using this project. I started using neo4j because I'm a little tired of SQL and mongo. And it seems there is many tooling missing in the Node world for neo.

**Pull request merged**
