### PR TITLE
fix: build from Dockerfile using 'as <stage>' in FROM clauses

### LINKED ISSUE #365: Multistage Dockerfile with private registries does not build
**Expected Behaviour**

A Dockerfile containing multiple stages that also uses private registries should build fine and use the provided auth configs.

**Actual Behaviour**

The AuthLocator always tries to get the credentials for the DEFAULT_REGISTRY "https://index.docker.io/v1/" as it tries to find auth configs based on the registries in the Dockerfile.

The getDockerFileImages from dockerfile-parser.ts does not respect the form `FROM <registry>/<image>:<tag> as <stage>` and returns no registry for the affected FROM statement.

**Testcontainer Logs**
...

**Steps to Reproduce**
1. Create a Dockerfile with the content `FROM cristianrgreco/testcontainer-private:1.1.12 as first-stage`
2. Try to build the Dockerfile using `GenericContainer.fromDockerfile(context).withPullPolicy(new AlwaysPullPolicy()).build()`
4. See error...

**Environment Information**
- Operating System: Windows 10
- Docker Version:  20.10.12
- Node version: 16.15.0
- Testcontainers version: 8.4.0

### PR DESCRIPTION
**Pull request by daviian**
Should fix #365

### CODE REVIEW

**Comment by daviian** [comment]
Sure, will do in a minute

**Comment by daviian** [comment]
Anything else you need from my side? Hope we can get this merged soon, as this is currently a blocker in a task of mine :D

**Review by cristianrgreco — APPROVED** [review]

**Comment by cristianrgreco** [comment]
@daviian Will get this merged/deployed as soon as the build passes. Atm this test is failing: 
`DockerfileParser › should work when formatted with spaces`

**Comment by daviian** [comment]
Oh no. I've updated the PR. The test should be fine now.

**Pull request merged**
