### PR TITLE
fix for "No Docker client strategy found" despite not invoked

### PR DESCRIPTION
**Pull request by calvintwr**
fix for https://github.com/testcontainers/testcontainers-node/issues/367

### CODE REVIEW

**Comment by cristianrgreco** [comment]
@calvintwr seems the PR is failing the tests

**Comment by calvintwr** [comment]
@cristianrgreco yea let me check it out.

**Comment by calvintwr** [comment]
@cristianrgreco can I get some help?

**Comment by calvintwr** [comment]
@cristianrgreco great got it thanks. i think in your suggestion, given that `getDockerClient` will be invoked, it might still result in the same issue. i'll see if I can come up with something, if not there might be practical fix for this. And honestly it doesn't require a fix. It just stands in the way when one tries to create abstractions.

**Comment by cristianrgreco** [comment]
> i think in your suggestion, given that getDockerClient will be invoked, it might still result in the same issue

That shouldn't be the case, `getDockerClient` is only invoked when `dockerClient()` is called, whereas before it was invoked when imported, so unless you call testcontainers code it shouldn't invoke, or am I missing something?

**Pull request closed without merging**
