### PR TITLE
Fix parsing registry from env variable to work with trailing slash

### PR DESCRIPTION
**Pull request by ilia-beliaev-miro**
Fixed the trailing slash in registry in env variable parsing behavior to work as specified in documentation.

### CODE REVIEW

**Comment by cristianrgreco** [comment]
@ilia-beliaev-miro do you know if this PR resolves https://github.com/testcontainers/testcontainers-node/issues/747 in its entirety?

**Comment by ilia-beliaev-miro** [comment]
> @ilia-beliaev-miro do you know if this PR resolves #747 in its entirety?

Hey @cristianrgreco, I can't test it with their setup. Maybe @ jonesbusy could check it?

**Comment by jonesbusy** [comment]
I don't think it resolve it. I was trying to remove the trailing slash from the env vars and the status was the same. Was hanging on the lock. Same if I remove the env vars (for the 10.8)

While this PR will avoid creating double slash, it doesn't fix the issues I have.

Right now I cannot explain further those regression with 10.7 and 10.8. Also why using same setup it work with testcontainer java et .net.

Using 10.7 which doesn't use the env vars, error is that the "Started" log message is not received. Which made me think it was related to changes on the  wait conditions.

**Comment by cristianrgreco** [comment]
@ilia-beliaev-miro is this PR ok to merge/release?

**Comment by ilia-beliaev-miro** [comment]
> @ilia-beliaev-miro is this PR ok to merge/release?

@cristianrgreco I am working on fixing the problem with the authentication with registry. Hope to push it in a couple of hours.

**Pull request merged**
