### PR TITLE
Select Docker host port binding according to resolved host IP family

### LINKED ISSUE #439: [Bug] Failed to connect to Reaper from 9.0.1
**Expected Behaviour**

Expected behaviour is that the reaper connects as it did in 9.0.0 and prior. I have stress tested older versions with multiple test-re-runs in the same environment and don't have any issues.

**Actual Behaviour**

Receive error log: `Failed to connect to Reaper [id]`, internally it follows multiple retries and `connect ECONNREFUSED ::1:32790`.

I believe it is as a result of this "patch" https://github.com/testcontainers/testcontainers-node/pull/412/files which has caused some kind of socket issue, though I am not sure specifically what is causing it within this code change

**Testcontainer Logs**

```
02:16:37.256Z testcontainers DEBUG Found applicable Docker client strategy: UnixSocketStrategy
02:16:37.257Z testcontainers DEBUG Testing Docker client strategy URI: unix:///var/run/docker.sock
02:16:37.297Z testcontainers INFO  Using Docker client strategy: UnixSocketStrategy, Docker host: localhost
02:16:37.297Z testcontainers DEBUG Fetching system diagnostics
02:16:37.302Z testcontainers DEBUG Found applicable registry auth locator for registry "https://index.docker.io/v1/": Auths
02:16:37.303Z testcontainers DEBUG Checking if image exists: postgres:14.4-alpine
02:16:37.309Z testcontainers DEBUG Not pulling image as it already exists: postgres:14.4-alpine
02:16:37.310Z testcontainers DEBUG Creating new Reaper for session: 8f6318d4de4e0c719345b275ea7ba304
02:16:37.313Z testcontainers DEBUG Re-using cached auth for registry https://index.docker.io/v1/
02:16:37.313Z testcontainers DEBUG Checking if image exists: testcontainers/ryuk:0.3.2
02:16:37.427Z testcontainers DEBUG Not pulling image as it already exists: testcontainers/ryuk:0.3.2
02:16:37.428Z testcontainers INFO  Creating container for image: testcontainers/ryuk:0.3.2
02:16:37.489Z testcontainers INFO  Starting container testcontainers/ryuk:0.3.2 with ID: ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce
02:16:37.895Z testcontainers DEBUG Waiting for container to be ready: ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce
02:16:37.895Z testcontainers DEBUG Waiting for log message "/.+ Started!/"
02:16:37.900Z testcontainers INFO  Container is ready
02:16:37.901Z testcontainers DEBUG Connecting to Reaper (attempt 1) ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce on localhost:32790
02:16:37.904Z testcontainers ERROR Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce socket error: Error: connect ECONNREFUSED ::1:32790
02:16:37.904Z testcontainers ERROR Connection to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce closed with error
02:16:38.203Z testcontainers DEBUG System diagnostics: {"node":{"version":"v18.13.0","architecture":"x64","platform":"linux"},"docker":{"serverVersion":"20.10.22+azure-1","operatingSystem":"Ubuntu 22.04.1 LTS","operatingSystemType":"linux","architecture":"x86_64","cpus":2,"memory":7281278976},"dockerCompose":{"version":"1.29.2"}}
02:16:38.906Z testcontainers DEBUG Connecting to Reaper (attempt 2) ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce on localhost:32790
02:16:38.908Z testcontainers ERROR Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce socket error: Error: connect ECONNREFUSED ::1:32790
02:16:38.908Z testcontainers ERROR Connection to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce closed with error
02:16:39.909Z testcontainers DEBUG Connecting to Reaper (attempt 3) ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce on localhost:32790
02:16:39.911Z testcontainers ERROR Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce socket error: Error: connect ECONNREFUSED ::1:32790
02:16:39.911Z testcontainers ERROR Connection to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce closed with error
02:16:40.912Z testcontainers DEBUG Connecting to Reaper (attempt 4) ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce on localhost:32790
02:16:40.913Z testcontainers ERROR Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce socket error: Error: connect ECONNREFUSED ::1:32790
02:16:40.913Z testcontainers ERROR Connection to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce closed with error
02:16:41.914Z testcontainers DEBUG Connecting to Reaper (attempt 5) ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce on localhost:32790
02:16:41.916Z testcontainers ERROR Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce socket error: Error: connect ECONNREFUSED ::1:32790
02:16:41.916Z testcontainers ERROR Connection to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce closed with error
[fatal]: Error: Failed to connect to Reaper ae242fdb1f5947148a8905de929dc1f80d5120cd93776bc4221a454ae43254ce\n    at /home/runner/work/backend/backend/node_modules/testcontainers/dist/reaper.js:126:56\n    at IntervalRetryStrategy.<anonymous> (/home/runner/work/backend/backend/node_modules/testcontainers/dist/retry-strategy.js:37:28)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/runner/work/backend/backend/node_modules/testcontainers/dist/retry-strategy.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Steps to Reproduce**

1. Ensure using testcontainer version `9.0.1` or later. 
 
2. Running testcontainers with simple Postgres and Redis startups defined by the following functions, we get infrequent issues with the testcontainer startup causing a test suite failure.

3. It does not happen consistently, perhaps 20% of the time. I also have not been able to replicate this locally.

```ts
export function createPostgresContainer(): PostgreSqlContainer {
  return new PostgreSqlContainer("postgres:14.4-alpine");
}

export function createRedisContainer(): GenericContainer {
  return new GenericContainer("redis:7-alpine")
    .withExposedPorts(6379)
    .withWaitStrategy(Wait.forLogMessage("Ready to accept connections"));
}
```

**Environment Information**

Issue only appears after upgrading to 9.0.1 containing this PR. Issue is resolved when downgrading to 9.0.0 or lower:

https://github.com/testcontainers/testcontainers-node/pull/412/files

- Operating System: Ubuntu 22.04.1  ( x86_64 Linux - Github Actions )
- Docker Version: 20.10.22
- Node version: 18.13
- Testcontainers version: 9.0.1

### PR DESCRIPTION
**Pull request by cristianrgreco**
Fixes #439 

Tested with:
- [x] Local (IPv6/IPv4)
- [x] GHA (IPv6/IPv4)
- [x] Codespaces (IPv4)
- [x] Remote Docker (IPv4)

### CODE REVIEW

**Review by HofmeisterAn — APPROVED** [review]
👍

**Review by kiview — APPROVED** [review]

**Comment by henrik242** [comment]
This didn't solve the IPv6 issue in Colima, it seems. Still have to workaround using 127.0.0.1 and set `TESTCONTAINERS_HOST_OVERRIDE=127.0.0.1`

**Comment by cristianrgreco** [comment]
That's correct @henrik242, this fix was specifically for Docker. Support for other container runtimes isn't yet defined. I am trying to improve the situation, see this PR where we've added limited Podman support, the Colima issue you mention is mentioned there as well: https://github.com/testcontainers/testcontainers-node/pull/494. 

If you know of ways we can better support Colima, without "adding code per container runtime", please raise an issue/start a discussion, I would very much like to improve our Colima support

**Comment by henrik242** [comment]
@cristianrgreco Thanks! I guess the root issue is https://github.com/lima-vm/lima/issues/1330

**Pull request merged**
